sudo: required
services:
    - docker

before_install:
    - docker build -t kingfabric2/complex-client-test -f ./client/Dockerfile.dev ./client # build using Dockerfile.dev
    
script:
    # [OLD VERSION] - docker run USERNAME/docker-react npm run test -- --coverage
    - docker run -e CI=true kingfabric2/complex-client-test npm run test

after_success:
    - docker build -t kingfabric2/complex-client ./client
    - docker build -t kingfabric2/complex-nginx ./nginx
    - docker build -t kingfabric2/complex-server ./server
    - docker build -t kingfabric2/complex-worker ./worker

# Log into the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push the images to the docker hub
    - docker push kingfabric2/complex-client
    - docker push kingfabric2/complex-nginx
    - docker push kingfabric2/complex-server
    - docker push kingfabric2/complex-worker

deploy:
    # we don't put - as it's not an array, it's 1 single object
    # Application:  docker-complex  
    # Environment: DockerComplex-env  
    # Environment ID: e-mmx6uuzqcm, URL: DockerComplex-env.eba-6xveejpb.ap-southeast-1.elasticbeanstalk.com
    
    # persistent missing bucket_name error with a failed build
    # this will force Travis to use the v2 (experimental) version of the dpl script which does not have the bug
    edge: true
    provider: elasticbeanstalk
    region: ap-southeast-1
    app: docker-complex
    env: DockerComplex-env
    # goto S3
    bucket_name: elasticbeanstalk-ap-southeast-1-907356006991
    bucket_path: docket-complex
    # only when push to master branch
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    # secret_access_key: <- previous version
    #    secure: $AWS_SECRET_KEY
    secret_access_key: $AWS_SECRET_KEY